version: 2
jobs:
  build-publish:

    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Clone all repos and run their build-test scripts
          command: |
            set -e
            ./sh/git-clone-all.sh
            ./sh/build-all.sh

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-publish:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
